"""Sample data loaded on first run."""

DOMAINS = [
    "Data Science", "Machine Learning", "Web Development", "Java Development",
    "Mobile Development", "Cyber Security", "Cloud & DevOps", "UI/UX Design",
]
LOCATIONS = ["Remote", "Bengaluru", "Hyderabad", "Pune", "Delhi NCR", "Mumbai", "Chennai"]
DURATIONS = [1, 2, 3, 4, 6]

# (title, company, domain, location, duration, stipend, description, [skills])
INTERNSHIPS = [
    ("Data Science Intern", "DataNest Analytics", "Data Science", "Bengaluru", 6, 20000,
     "Work on real datasets, build predictive models and dashboards.",
     ["Python", "SQL", "Machine Learning", "Pandas", "Statistics"]),
    ("Machine Learning Intern", "NeuralWorks", "Machine Learning", "Remote", 6, 25000,
     "Train and evaluate ML models for classification and recommendation tasks.",
     ["Python", "Machine Learning", "NumPy", "Scikit-learn"]),
    ("Data Analyst Intern", "InsightHub", "Data Science", "Pune", 3, 12000,
     "Clean data, write SQL queries and build Excel/BI reports.",
     ["SQL", "Excel", "Python", "Power BI"]),
    ("AI Intern", "Cogniva Labs", "Machine Learning", "Hyderabad", 4, 22000,
     "Prototype AI features including NLP and computer vision pipelines.",
     ["Python", "Machine Learning", "Deep Learning", "TensorFlow"]),
    ("Frontend Web Developer Intern", "PixelCraft", "Web Development", "Remote", 3, 10000,
     "Build responsive user interfaces for client websites.",
     ["HTML", "CSS", "JavaScript", "React"]),
    ("Full Stack Intern", "StackBridge", "Web Development", "Delhi NCR", 6, 18000,
     "Develop end-to-end features with a Python backend and SQL database.",
     ["HTML", "CSS", "JavaScript", "Python", "Flask", "SQL"]),
    ("Backend Developer Intern", "ServeLogic", "Web Development", "Bengaluru", 4, 15000,
     "Design REST APIs and optimise database queries.",
     ["Python", "Django", "SQL", "REST API", "Git"]),
    ("Java Development Intern", "JavaWorks Technologies", "Java Development", "Chennai", 6, 15000,
     "Develop enterprise modules using Java and Spring Boot.",
     ["Java", "SQL", "Spring Boot", "Git"]),
    ("Android App Intern", "AppForge", "Mobile Development", "Mumbai", 3, 12000,
     "Build and test Android features using Kotlin.",
     ["Kotlin", "Java", "Android", "Git"]),
    ("Cyber Security Intern", "SecureNet", "Cyber Security", "Remote", 3, 14000,
     "Assist in vulnerability assessments and security monitoring.",
     ["Networking", "Linux", "Python", "Cyber Security"]),
    ("Cloud & DevOps Intern", "CloudSpan", "Cloud & DevOps", "Pune", 6, 20000,
     "Automate deployments and manage CI/CD pipelines.",
     ["Linux", "Docker", "Git", "AWS", "CI/CD"]),
    ("UI/UX Design Intern", "DesignDen", "UI/UX Design", "Remote", 2, 9000,
     "Create wireframes, prototypes and user-research reports.",
     ["Figma", "Wireframing", "User Research", "HTML", "CSS"]),
]

# Course suggestions for missing skills (skill name lower-case -> course)
COURSES = {
    "statistics": "Statistics for Data Science (Coursera / NPTEL)",
    "pandas": "Data Analysis with Pandas (Kaggle Learn)",
    "numpy": "NumPy Basics (Kaggle Learn / freeCodeCamp)",
    "scikit-learn": "Machine Learning with Scikit-learn (Coursera)",
    "machine learning": "Machine Learning Specialization (Coursera)",
    "deep learning": "Deep Learning Specialization (Coursera)",
    "tensorflow": "TensorFlow Developer Certificate Prep (Coursera)",
    "sql": "SQL for Beginners (Khan Academy / W3Schools)",
    "python": "Python for Everybody (Coursera)",
    "excel": "Excel Skills for Business (Coursera)",
    "power bi": "Microsoft Power BI Data Analyst (Microsoft Learn)",
    "html": "Responsive Web Design (freeCodeCamp)",
    "css": "Responsive Web Design (freeCodeCamp)",
    "javascript": "JavaScript Algorithms & Data Structures (freeCodeCamp)",
    "react": "React - The Complete Guide (Udemy / react.dev)",
    "flask": "Flask Mega-Tutorial (Miguel Grinberg)",
    "django": "Django for Beginners (Official Django Tutorial)",
    "rest api": "APIs for Beginners (freeCodeCamp)",
    "git": "Git & GitHub Crash Course (freeCodeCamp)",
    "java": "Java Programming Masterclass (Udemy / NPTEL)",
    "spring boot": "Spring Boot Tutorial (Baeldung / Spring Guides)",
    "kotlin": "Android Basics with Kotlin (Google)",
    "android": "Android Basics with Kotlin (Google)",
    "networking": "Computer Networking Fundamentals (Cisco NetAcad)",
    "linux": "Linux for Beginners (Linux Foundation)",
    "cyber security": "Google Cybersecurity Certificate (Coursera)",
    "docker": "Docker for Beginners (Docker Docs)",
    "aws": "AWS Cloud Practitioner Essentials (AWS Skill Builder)",
    "ci/cd": "CI/CD with GitHub Actions (GitHub Docs)",
    "figma": "Figma UI Design Tutorial (Figma Learn)",
    "wireframing": "Intro to UX Design (Google / Coursera)",
    "user research": "User Research Fundamentals (Interaction Design Foundation)",
}
